### ISSUE TITLE
Clarification on alignment constraints for LPCLL

### ISSUE THREAD

**Issue by MarkHillHuawei** [riscv/riscv-cfi#25]
Could someone clarify why there is an alignment constraint on the lpcll instruction. This would, for example, prevent the use of the -fno-align-functions gcc/clang compiler option. I can't think of any architectural reason for the constraint, perhaps there is some benefit from in deeply pipelined microarchitectures but I can't see a universal reason for this.

Very well written spec by the way!

**Comment by ved-rivos** [comment]
The `lpcll` is a 4B instruction. A condition to avoid is say there are two 4B instructions (A, B) and a branch occurs to middle of A and there by the 2B pattern of A concatenated with 2B pattern of B is consumed as a `lpcll` instruction. This is the reason to place this constraint. The compiler would be expected to align when compiled for CFI the `lpcll` to the 4B boundary.

**Comment by sorear** [comment]
I don't think this is sufficient to prevent unintentional landing pads, because even if a `lpcll` is required to be at a 0 mod 4 address, it could be constructed from `A` and `B` both of which are 32-bit instructions at a 2 mod 4 address, or `A` which is a 48+-bit instruction at a 2 mod 4 address.

In RV64GC the problematic pairs consist of a 32-bit instruction with a second parcel of `4073` or `C073` (consisting of instructions of all types, including immediate fields of lui/auipc/jal instructions which are only populated at link time), followed by a 16- or 32-bit instruction with a second byte of `83` (including a large fraction of instructions which write to t1 or t2, `sb` with a displacement of 6 or 7, `beq` skipping 2 mod 16 parcels, and special cases of `c.srli` and c.jr`).

A possible fix would be for the assembler to align any instruction which could become an `A` to 0 mod 4 (thus forcing the resulting `lpcll` bit pattern to be misaligned and invalid).  This is necessarily conservative for instructions for which a relocation is generated, imposing an average 1 byte penalty on all symbol accesses; avoiding that would require a new relocation type that only aligns if the result would otherwise be confusable with a lpcll instruction.

**Comment by ved-rivos** [comment]
That was the intent of the alignment to reduce the search space for the assembler to perform this fix.

**Comment by ved-rivos** [comment]
Moved the clarification into text with PR #56
